### ISSUE TITLE
Super Mario Bros 64 (SM64 Mod) (Playable)

### ISSUE THREAD

**Issue by Smoker1** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#102]
# Game summary
- Game name: Super Mario Bros 64 (Mod)
- Game version: 

# Daedalus X64 summary
- Version: Latest Available on 6 May 20 @1230 AM

# Issues

# Screenshots
![](https://?)

# Recommended labels

- A?
- B?
- C?

**Comment by Rinnegatamante** [comment]
Better not to insert mods in this list.
