### ISSUE TITLE
Donkey Kong 64

### ISSUE THREAD

**Issue by holictsubasa** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#123]
# Game summary
- Game name: Donkey Kong 64
- Game version: EU

# Daedalus X64 summary
- Version: v0.2

# Issues
Crash in rom selection menu in v0.2 with or without dynarec

# Recommended labels

- Crash

**Comment by Rinnegatamante** [comment]
US version should work fine.

**Comment by Rinnegatamante** [comment]
Also duplicate
