### ISSUE TITLE
All Star Tennis 99

### ISSUE THREAD

**Issue by Invictaz** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#152]
# Game summary
- Game name: All Star Tennis 99
- Game version: USA

# Daedalus X64 summary
- Version: v0.2 TheFlow Build 21.00hr 11-5-2020

# Issues
Crashes with dynarec on after the first intro. With dynarec off it reaches the menu but is below 5fps so unbearable to test, even with all buffering options set to on to speedhack.

**Comment by Rinnegatamante** [comment]
Can you try on latest nightly?
