### ISSUE TITLE
Conker's Bad Fur Day

### ISSUE THREAD

**Issue by Astralogers** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#173]
# Game summary
- Game name: Conker's Bad Fur Day
- Game version: US EU

# Daedalus X64 summary
- Version: v0.3

# Issues

#  Dynarec Enabled

The game crashes on the initial screen of "For Mature Audiencies Only"

# Dynarec disabled

Approximately 2.1-5 fps in menus and initial cinematics.
It comes into play and has around 3-5 fps.
The game does not present any graphic bug

# Screenshots
![2020-05-18-111854](https://user-images.githubusercontent.com/65482932/82240045-5cd88e80-98ff-11ea-833f-04144e82bb9a.jpg)

![2020-05-18-112141](https://user-images.githubusercontent.com/65482932/82240157-8e515a00-98ff-11ea-9da3-c2023bdde0be.jpg)

![2020-05-18-112426](https://user-images.githubusercontent.com/65482932/82240259-b476fa00-98ff-11ea-8516-22e7c7edb64e.jpg)

![2020-05-18-112518](https://user-images.githubusercontent.com/65482932/82240284-c48ed980-98ff-11ea-8171-6ed8f76c822e.jpg)

# Recommended labels

The game does not present any graphical error with dynarec disabled, but it works (it does not crash) at low fps compared to v0.1 with the same game.

It is playable BUT with very low fps in this version

**Comment by Rinnegatamante** [comment]
Please add your reports on existing Issues: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/77
