### ISSUE TITLE
Conker's Bad Fur Day

### ISSUE THREAD

**Issue by Astralogers** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#174]
# Game summary
- Game name: Conker's Bad Fur Day
- Game version: US EU

# Daedalus X64 summary
- Version: vNightly to date 05/18/20

# Issues

#  DynaRec Unsafe

The game crashes on the initial screen of "For Mature Audiencies Only" same as in v0.3

# DynaRec Safe

Approximately 8-14.5 fps in menus and initial cinematics.
It comes into play and has around 15 fps.
The game presents many graphic bugs in the 3d models of the characters: 3D models glitching and return to normal for a moment and resize at times (Screenshots)

# Screenshots

![2020-05-18-113429](https://user-images.githubusercontent.com/65482932/82241559-fb65ef00-9901-11ea-849c-e6371160a160.jpg)

![2020-05-18-113439](https://user-images.githubusercontent.com/65482932/82241608-10428280-9902-11ea-8296-f3e9148ed1f9.jpg)

![2020-05-18-113948](https://user-images.githubusercontent.com/65482932/82241908-8f37bb00-9902-11ea-9f90-6b3cb6836d1e.jpg)

![2020-05-18-114334](https://user-images.githubusercontent.com/65482932/82241951-9b237d00-9902-11ea-8b41-4f6254777531.jpg)

![2020-05-18-114514](https://user-images.githubusercontent.com/65482932/82242143-f81f3300-9902-11ea-8ba6-8c22f4ae833f.jpg)

![2020-05-18-114523](https://user-images.githubusercontent.com/65482932/82242172-053c2200-9903-11ea-9289-39eae12d42ca.jpg)

# Recommended labels

The game has many graphic errors, especially 3D models glitching.

The only advantage is that it works at better FPS than in the latest version 0.3 (until 05/18/20)

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/77
