### ISSUE TITLE
Army Men: Sarge's Heroes 2

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#177]
# Game summary
- Game name: Army Men: Sarge's Heroes
- Game version: 1.0 E/U

# Daedalus X64 summary
- Version: v0.3 2020/05/20 Nightly

# Issues
Almost perfect, everything works, just game play is slow and none of the options will speed it up.

**Comment by Sarkie** [comment]
Seems to only use 1 core during game play a lot of the time.

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/162

**Comment by Sarkie** [comment]
this is the sequel.

**Comment by Rinnegatamante** [comment]
Army Men: Sarge's Heroes 2 is not the sequel of Army Men: Sarge's Heroes 2.

**Comment by Sarkie** [comment]
Ha! Sorry I read what I wanted to read. It just wasn't showing in the app with a label
