### ISSUE TITLE
Dr. Mario 64

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#193]
# Game summary
- Game name: Dr. Mario 64
- Game version: USA

# Daedalus X64 summary
- Version: v0.3 nightly

# Issues

Once in game, the background textures are very corrupted so can't really play

# Screenshots
![](https://?)

# Recommended labels

- A?
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/175
