### ISSUE TITLE
Diddy Kong Racing

### ISSUE THREAD

**Issue by hidagyuu** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#197]
# Game summary
- Game name: Diddy Kong Racing
- Game version: Japan

# Daedalus X64 summary
- Version: v0.3 nightly

# Issue
 menu very slow fps. Other languages ​​work fine.  By the way v0.2 is normal,

# Screenshots
![](https://?
![IMG_6532](https://user-images.githubusercontent.com/67532990/85939324-49cdcb00-b94f-11ea-88e8-5f33b55d8fc6.jpg)
)

# Recommended labels

- A?
- B?
- C?

**Comment by Rinnegatamante** [comment]
A report page for this game is already opened, please post your reports there: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/49
