### ISSUE TITLE
Blast Corps

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#200]
# Game summary
- Game name: Blast Corps
- Game version: v1.0, USA

# Daedalus X64 summary
- Version: v0.4

# Issues
Crashes after the Rareware logo.

# Screenshots
![](https://?)

# Recommended labels

- A? Crash
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/38
