### ISSUE TITLE
Yoshi's Story

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#203]
# Game summary
- Game name: Yoshi's Story 
- Game version: USA

# Daedalus X64 summary
- Version: v0.4

# Issues
Audio pitch is slightly wobbly. There is occassional slowdown. The page-turning transition, when going from area to area, has a big white square that blocks most of the screen. A few textures in the environment have tears and fewer of them have transparent squares. Overall, the game is enjoyable. I just wouldn't recommend anyone to use headphones.

# Screenshots
![](https://?)

# Recommended labels

- A? Playable
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/39
