### ISSUE TITLE
Paper Mario - New File Crash

### ISSUE THREAD

**Issue by ianmckinney** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#232]
# Game summary
- Game name: Paper Mario
- Game version: US

# Daedalus X64 summary
- Version: v0.4 and 7/6 Nightly

# Issues

Emulator crashes when starting a new game

# Screenshots
![](https://user-images.githubusercontent.com/25875170/84470245-c5353a00-ac37-11ea-937d-7016e807821a.jpg)

# Recommended labels

- A? Crash
- B?
- C?

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/13
