### ISSUE TITLE
Mario Kart 64

### ISSUE THREAD

**Issue by ErectricBass** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#233]
# Game summary
- Game name: Mario Kart 64
- Game version: US

# Daedalus X64 summary
- Version: v4

# Issues
Screen goes completely black when you finish a cup, with distorted audio. Can’t get past that screen and forced to reset. Also doesn’t save time trial scores.

# Recommended labels

- Unplayable

**Comment by Rinnegatamante** [comment]
Duplicate https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/2
