### ISSUE TITLE
All Star Tennis '99

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#236]
Game summary
Game name: All Star Tennis '99
Game version: USA
Daedalus X64 summary
Version: v0.4 nightly
Issues:
None

Recommended labels
playable

**Comment by animekai** [comment]
This name is correct but duplicated with https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/157
