### ISSUE TITLE
Extreme-G XG2

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#279]
# Game summary
- Game name: Extreme-G XG2
- Game version: USA

# Daedalus X64 summary
- Version: v0.4 nightly

# Issues

None

# Screenshots
![](https://?)

# Recommended labels

Playable
- A?
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/126
