### ISSUE TITLE
Star Wars - Shadows of the Empire (EU)

### ISSUE THREAD

**Issue by Invictaz** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#34]
# Game summary
- Game name: Star Wars - Shadows of the Empire
- Game version: EU

# Daedalus X64 summary
- Version: v0.1 alpha

# Issues
Black background with blue bars.
Takes some time to startup
Flickering logo's.
This is a factor 5 game with a lot of custom ucode
Ingame 60FPS. Flickering but playable. Misses some models or parts of them.
Intro is slow.

**Comment by SeongGino** [comment]
Sounds a lot like the US version I reported earlier; probably the only difference being the 50/60hz mixup between regions.

**Comment by Invictaz** [comment]
Maybe we should merge the issues then

**Comment by Rinnegatamante** [comment]
Ditto of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/19
