### ISSUE TITLE
WCW vs. nWo - World Tour

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#345]
# Game summary
- Game name: WCW vs. nWo - World Tour (v1.1)
- Game version: USA

# Daedalus X64 summary
- Version: v0.4 Nightly

# Issues

Crashes on load for any CPU type

# Screenshots
![](https://?)

# Recommended labels

- A Crash
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/161
