### ISSUE TITLE
Banjo-Kazooie

### ISSUE THREAD

**Issue by Lagetar** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#37]
# Game summary
- Game name: Banjo-Kazooie
- Game version: (USA) (Rev 1)

# Daedalus X64 summary
- Version: v.0.1

# Issues

Audio enabled and Vita is overclocked with PSVshell. Game crashes when loading the menu. Gameplay performance seems to oscillate from 17-23FPS from the demo scenes of the start screen, The intro songs tops a 20FPS.

# Screenshots
![](https://i.imgur.com/oUHd4c5.png)

# Recommended labels

- A?
- B?
- C?

**Comment by Rinnegatamante** [comment]
Ditto https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/36
