### ISSUE TITLE
Puyo Puyo 4 - Puyo Puyon Party

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#450]
# Game summary
- Game name: Puyo Puyo 4 - Puyo Puyon Party
- Game version: Japan

# Daedalus X64 summary
- Version: v0.4

# Issues

menus are gigantic, and gameplay too,not playable
# Screenshots

![2020-08-03-185613-211159](https://user-images.githubusercontent.com/32076097/89238281-1cfa7c80-d5bb-11ea-99d6-5a0d85b2bb59.png)
![2020-08-03-185634-599022](https://user-images.githubusercontent.com/32076097/89238283-1e2ba980-d5bb-11ea-8702-660a3f8b67fa.png)

# Recommended labels

- A Ingame+
- B?
- C?

**Comment by Shinriji** [comment]
Same as #132
