### ISSUE TITLE
Superman

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#480]
# Game summary
- Game name: Superman
- Game version: USA

# Daedalus X64 summary
- Version: v0.4

# Issues

This beta runs fine i guess, with textures missing, playable
# Screenshots
![2020-08-04-185927-435915](https://user-images.githubusercontent.com/32076097/89356988-e25d1680-d684-11ea-8eb7-75a086927cd6.png)
![2020-08-04-185936-228257](https://user-images.githubusercontent.com/32076097/89356990-e2f5ad00-d684-11ea-99f4-2cffdbcc47ea.png)
![2020-08-04-185947-022553](https://user-images.githubusercontent.com/32076097/89356991-e38e4380-d684-11ea-9718-d19dd91506ff.png)
![2020-08-04-185958-717451](https://user-images.githubusercontent.com/32076097/89356992-e38e4380-d684-11ea-87a0-e9045319a947.png)
![2020-08-04-190011-981363](https://user-images.githubusercontent.com/32076097/89356993-e38e4380-d684-11ea-810d-4d309da500dc.png)

# Recommended labels

- A Ingame+
- B?
- C?

**Comment by HELLOcommaWORLD** [comment]
#11 (?)

**Comment by animekai** [comment]
this is a prototipe, i dont know if had to be merged with the main game, but in roms,ini is a separate rom

**Comment by Rinnegatamante** [comment]
Better to rename the game in roms.ini indeed.

**Comment by animekai** [comment]
@Rinnegatamante  still untagged, crc is: c4af4f946a2688b2-0

**Comment by Rinnegatamante** [comment]
Update data files...

**Comment by animekai** [comment]
yeah ive done that but stills, is weird XD

**Comment by animekai** [comment]
i see the error:
![image](https://user-images.githubusercontent.com/32076097/89436159-75409400-d70b-11ea-9e23-631ccceed6c2.png)
The beta crc end with -0 not -45
