### ISSUE TITLE
DK64 suddenly crashes/runs like crap

### ISSUE THREAD

**Issue by opseto** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#510]
DK64 was the first rom I tested with daedalusx64 and it worked just fine. However after deleting it some time ago, and now re-adding the rom to the rom folder for daedalusx64 results in the game crashing after it says "donkey!" followed by tv white noise as video for about 30secs. Can't skip past it. 

I've tried several different rom sources, deleting playtime files and save game files and flash save files, but nothing seems to "revert" the rom back to normal?

**Comment by Rinnegatamante** [comment]
Disable Loop Optimizations in DynaRec Config. Also refer to existing issues for games and do not open other issues isntead.
