### ISSUE TITLE
Pokemon Snap

### ISSUE THREAD

**Issue by BubberDunk** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#511]
# Game summary
- Game name: Pokemon Snap
- Game version: ?

# Daedalus X64 summary
- Version: v.0.6

# Issues
Game runs fine, though there are some framerate issues
Photo's taken in game are black boxes, preventing any progression 

# Screenshots

![2021-02-16-160927](https://user-images.githubusercontent.com/7241703/108137919-bed24a00-7071-11eb-84bc-9a3e62d86b38.jpg)

# Recommended labels

- A Ingame+
- B?
- C?

**Comment by Rinnegatamante** [comment]
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/154
