### ISSUE TITLE
Pyoro 64 not showing full screen 

### ISSUE THREAD

**Issue by thalyy36** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#514]
DaedalusX64 doesn't show the full screen of the homebrew game Pyoro 64, no matter the resolution I select, I only get a chunck of the screen of this game, attached is an image of how it looks like.

![2021-07-04-193409](https://user-images.githubusercontent.com/44348544/124518641-546e3c00-ddbd-11eb-9b2b-075c2403b363.jpg)

**Comment by Rinnegatamante** [comment]
Please properly format the post (Title must be same exact game name that daedalusx64 shows)

**Comment by thalyy36** [comment]
My apologies, I'm not at all well versed with GitHub
