### ISSUE TITLE
Paper Mario Menu Issues

### ISSUE THREAD

**Issue by Gongoozie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#517]
Hey, just recently got into emulating n64 games on my ps vita using DaedalusX64.
I'm trying to play Paper Mario and the menu is not loading correctly. It'll flash the correct menu visuals for a second but then a weird version of it pops up, completely covered in black and white boxes and making it difficult to see anything in the menu. Is this just an issue with the game on the emulator, or can I change something in the settings so that this issue is fixed? I would really appreciate any help! Thank you in advance :)

**Comment by Gongoozie** [comment]
Additionally, when starting a battle with an enemy, it just shows a weird glitchy black screen and then starts the battle. Not a huge issue with running the game, but would be nice if I could change that as well.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/13 report those here.
